services:
   db:
     image: mysql:5.7
     volumes:
       - db_data_std00:/var/lib/mysql # TODO: Bitte die Benutzernummer anpassen!
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8400:80" # TODO: Bitte (linken) Port an die Benutzernummer anpassen    !
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data_std00: {} # TODO: Bitte die Benutzernummer anpassen!
